In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('multireg.csv')

In [3]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [5]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [6]:
reg = LinearRegression()

In [7]:
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909486

In [10]:
reg.score(x,y)

0.40668119528142843

### Formula for ADJ R^2
R^2(adj)=1-(1-R^2)*(n-1)/(n-p-1)

In [11]:
x.shape

(84, 2)

In [12]:
r2=reg.score(x,y)

n=x.shape[0]

p=x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

# Feature selection

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [15]:
p_values = f_regression(x,y)[1]
p_values


array([7.19951844e-11, 6.76291372e-01])

In [16]:
p_values.round(3)

array([0.   , 0.676])

# Creating a summary table

In [18]:
reg_summery = pd.DataFrame(data =x.columns.values,columns=['Features'])
reg_summery

Features
0         SAT
1  Rand 1,2,3

In [19]:
reg_summery ['Coefficients'] = reg.coef_
reg_summery ['p-values'] = p_values.round(3)

In [20]:
reg_summery

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

# Standardization

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
scaler.fit(x)

StandardScaler()

In [24]:
x_scaled = scaler.transform(x)

In [25]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with scaled features

In [26]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [27]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [28]:
reg.intercept_

3.330238095238095

# Creating Summary Table

In [31]:
reg_summery = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summery['weights'] =reg.intercept_,reg.coef_[0],reg.coef_[1]

In [32]:
reg_summery

Features   weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Making Prediction

In [33]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [34]:
reg.predict(new_data)

C:\Users\Vozon Comsof Pvt Ltd\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [35]:
new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [36]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])